[package]
name = "elm-dedup-project"
version = "0.1.0"
edition = "2021"

[dependencies]
rayon = "1.5"
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.20", features = ["macros", "rt", "rt-multi-thread"] }
